# Generated by Django 3.2.12 on 2022-03-25 09:47

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('myapp430', '0006_coaches'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='coaches',
            new_name='coach',
        ),
        migrations.RenameModel(
            old_name='fans',
            new_name='fan',
        ),
        migrations.RenameModel(
            old_name='OrderTickets',
            new_name='OrderTicket',
        ),
        migrations.RenameModel(
            old_name='shop',
            new_name='ShopItem',
        ),
        migrations.RenameModel(
            old_name='tickets',
            new_name='ticket',
        ),
        migrations.RenameModel(
            old_name='trainees',
            new_name='trainee',
        ),
    ]
