# Generated by Django 3.2.12 on 2022-03-25 10:39

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('myapp430', '0007_auto_20220325_1147'),
    ]

    operations = [
        migrations.AddField(
            model_name='ordershop',
            name='coach',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='myapp430.coach'),
        ),
        migrations.AddField(
            model_name='ordershop',
            name='fan',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='myapp430.fan'),
        ),
        migrations.AddField(
            model_name='ordershop',
            name='shop_item',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='myapp430.shopitem'),
        ),
        migrations.AddField(
            model_name='ordershop',
            name='trainee',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='myapp430.trainee'),
        ),
        migrations.AddField(
            model_name='orderticket',
            name='coach',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='myapp430.coach'),
        ),
        migrations.AddField(
            model_name='orderticket',
            name='fan',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='myapp430.fan'),
        ),
        migrations.AddField(
            model_name='orderticket',
            name='order_ticket',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='myapp430.ticket'),
        ),
        migrations.AddField(
            model_name='orderticket',
            name='trainee',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='myapp430.trainee'),
        ),
    ]
