# Generated by Django 3.2.12 on 2022-03-25 10:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp430', '0008_auto_20220325_1239'),
    ]

    operations = [
        migrations.CreateModel(
            name='Tag',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200, null=True)),
            ],
        ),
        migrations.AlterField(
            model_name='shopitem',
            name='category',
            field=models.CharField(choices=[('Clothes', 'Clothes'), ('Shoes', 'Shoes'), ('Accessories', 'Accessories')], max_length=200),
        ),
        migrations.AddField(
            model_name='ordershop',
            name='tags',
            field=models.ManyToManyField(to='myapp430.Tag'),
        ),
    ]
