# Generated by Django 3.2.12 on 2022-03-25 10:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp430', '0009_auto_20220325_1246'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='ordershop',
            name='tags',
        ),
        migrations.AddField(
            model_name='shopitem',
            name='tags',
            field=models.ManyToManyField(to='myapp430.Tag'),
        ),
    ]
