# Generated by Django 3.2.12 on 2022-03-25 10:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp430', '0010_auto_20220325_1249'),
    ]

    operations = [
        migrations.AlterField(
            model_name='shopitem',
            name='category',
            field=models.CharField(choices=[('BasketBall', 'BasketBall'), ('FootBall', 'FootBall')], max_length=200),
        ),
    ]
