# Generated by Django 3.2.12 on 2022-03-25 10:53

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('myapp430', '0011_alter_shopitem_category'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='shopitem',
            name='tags',
        ),
    ]
