# Generated by Django 3.2.12 on 2022-03-25 10:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp430', '0013_shopitem_tags'),
    ]

    operations = [
        migrations.AlterField(
            model_name='coach',
            name='email',
            field=models.CharField(max_length=200, null=True),
        ),
        migrations.AlterField(
            model_name='coach',
            name='name',
            field=models.CharField(max_length=200, null=True),
        ),
        migrations.AlterField(
            model_name='coach',
            name='phone',
            field=models.CharField(max_length=200, null=True),
        ),
        migrations.AlterField(
            model_name='fan',
            name='email',
            field=models.CharField(max_length=200, null=True),
        ),
        migrations.AlterField(
            model_name='fan',
            name='name',
            field=models.CharField(max_length=200, null=True),
        ),
        migrations.AlterField(
            model_name='fan',
            name='phone',
            field=models.CharField(max_length=200, null=True),
        ),
        migrations.AlterField(
            model_name='ordershop',
            name='status',
            field=models.CharField(choices=[('Pending', 'Pending'), ('Out for delivery', 'Out for delivery'), ('Delivered', 'Delivered')], max_length=200, null=True),
        ),
        migrations.AlterField(
            model_name='orderticket',
            name='status',
            field=models.CharField(choices=[('Pending', 'Pending'), ('Paid', 'Paid')], max_length=200, null=True),
        ),
        migrations.AlterField(
            model_name='shopitem',
            name='category',
            field=models.CharField(choices=[('BasketBall', 'BasketBall'), ('FootBall', 'FootBall')], max_length=200, null=True),
        ),
        migrations.AlterField(
            model_name='shopitem',
            name='descirption',
            field=models.CharField(max_length=200, null=True),
        ),
        migrations.AlterField(
            model_name='shopitem',
            name='name',
            field=models.CharField(max_length=200, null=True),
        ),
        migrations.AlterField(
            model_name='ticket',
            name='category',
            field=models.CharField(choices=[('BasketBall', 'BasketBall'), ('FootBall', 'FootBall')], max_length=200, null=True),
        ),
        migrations.AlterField(
            model_name='ticket',
            name='descirption',
            field=models.CharField(max_length=200, null=True),
        ),
        migrations.AlterField(
            model_name='ticket',
            name='name',
            field=models.CharField(max_length=200, null=True),
        ),
        migrations.AlterField(
            model_name='trainee',
            name='email',
            field=models.CharField(max_length=200, null=True),
        ),
        migrations.AlterField(
            model_name='trainee',
            name='name',
            field=models.CharField(max_length=200, null=True),
        ),
        migrations.AlterField(
            model_name='trainee',
            name='phone',
            field=models.CharField(max_length=200, null=True),
        ),
    ]
