# Generated by Django 3.2.12 on 2022-03-25 11:13

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('myapp430', '0014_auto_20220325_1259'),
    ]

    operations = [
        migrations.AlterField(
            model_name='ordershop',
            name='coach',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='myapp430.coach'),
        ),
        migrations.AlterField(
            model_name='ordershop',
            name='fan',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='myapp430.fan'),
        ),
        migrations.AlterField(
            model_name='ordershop',
            name='trainee',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='myapp430.trainee'),
        ),
        migrations.AlterField(
            model_name='orderticket',
            name='coach',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='myapp430.coach'),
        ),
        migrations.AlterField(
            model_name='orderticket',
            name='fan',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='myapp430.fan'),
        ),
        migrations.AlterField(
            model_name='orderticket',
            name='trainee',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='myapp430.trainee'),
        ),
    ]
