# Generated by Django 3.2.12 on 2022-04-01 07:05

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('myapp430', '0015_auto_20220325_1313'),
    ]

    operations = [
        migrations.RenameField(
            model_name='shopitem',
            old_name='descirption',
            new_name='description',
        ),
    ]
