# Generated by Django 3.2.12 on 2022-03-27 17:19

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('base1', '0002_fan_user'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='fan',
            name='user',
        ),
    ]
