# Generated by Django 3.2.12 on 2022-03-29 16:47

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('base1', '0005_profile'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Profile',
        ),
    ]
