# Generated by Django 3.2.12 on 2022-03-29 16:58

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('base1', '0007_user'),
    ]

    operations = [
        migrations.DeleteModel(
            name='User',
        ),
    ]
